"""CTPF kernel: trust-transition records, oracles, and evidence bundles.

Public API is re-exported from :mod:`ctpf.kernel.slice` (Pattern 2 + cascade).
No CLI verbs here — library only.
"""

from __future__ import annotations

from ctpf.kernel.slice import (
    ARTIFACTS_DIRNAME,
    BASELINE_SESSION_A_TRACE_NAME,
    BASELINE_SESSION_B_TRACE_NAME,
    BASELINE_TRACE_NAME,
    CONDITION_BASELINE,
    CONDITION_MANIPULATED,
    MANIFEST_NAME,
    MANIPULATED_MEMO_NAME,
    MANIPULATED_SESSION_A_TRACE_NAME,
    MANIPULATED_SESSION_B_TRACE_NAME,
    MANIPULATED_SINK_NAME,
    MANIPULATED_TRACE_NAME,
    MEMO_EFFECT_KEY,
    MEMO_WRITTEN_VALUE,
    REQUIRED_CASCADE_SPLIT_TRACE_NAMES,
    REQUIRED_CONFIRMED_CASCADE_ARTIFACTS,
    REQUIRED_TRACE_NAMES,
    RESULT_NAME,
    SINK_APPLIED_VALUE,
    SINK_EFFECT_KEY,
    CascadeArmObservation,
    CascadeExperimentContext,
    CascadeMemoScenario,
    EvidenceBundle,
    ExperimentContext,
    ExperimentPins,
    ExternalEffect,
    Pattern2Scenario,
    PromotionResult,
    RunObservation,
    TrustTransition,
    compare_baseline_manipulated,
    compare_cascade_baseline_manipulated,
    observe_memo_persistence,
    observe_sink_effect,
    sha256_file,
    write_cascade_evidence_bundle,
    write_evidence_bundle,
)
from ctpf.kernel.trace import parse_cascade_arm_traces, parse_pattern2_trace

__all__ = [
    "ARTIFACTS_DIRNAME",
    "BASELINE_SESSION_A_TRACE_NAME",
    "BASELINE_SESSION_B_TRACE_NAME",
    "BASELINE_TRACE_NAME",
    "CONDITION_BASELINE",
    "CONDITION_MANIPULATED",
    "MANIFEST_NAME",
    "MANIPULATED_MEMO_NAME",
    "MANIPULATED_SESSION_A_TRACE_NAME",
    "MANIPULATED_SESSION_B_TRACE_NAME",
    "MANIPULATED_SINK_NAME",
    "MANIPULATED_TRACE_NAME",
    "MEMO_EFFECT_KEY",
    "MEMO_WRITTEN_VALUE",
    "REQUIRED_CASCADE_SPLIT_TRACE_NAMES",
    "REQUIRED_CONFIRMED_CASCADE_ARTIFACTS",
    "REQUIRED_TRACE_NAMES",
    "RESULT_NAME",
    "SINK_APPLIED_VALUE",
    "SINK_EFFECT_KEY",
    "CascadeArmObservation",
    "CascadeExperimentContext",
    "CascadeMemoScenario",
    "EvidenceBundle",
    "ExperimentContext",
    "ExperimentPins",
    "ExternalEffect",
    "Pattern2Scenario",
    "PromotionResult",
    "RunObservation",
    "TrustTransition",
    "compare_baseline_manipulated",
    "compare_cascade_baseline_manipulated",
    "observe_memo_persistence",
    "observe_sink_effect",
    "parse_cascade_arm_traces",
    "parse_pattern2_trace",
    "sha256_file",
    "write_cascade_evidence_bundle",
    "write_evidence_bundle",
]
