"""Run-level guidance models for research workflow playbooks.

RunGuidance is a per-run, structured guidance object generated by module
adapters at run creation time and attached to the run record. It is separate
from MitigationGuidance (which is per-finding and generated by the
MitigationResolver for audit findings).

Data models:
- BlockKind: StrEnum for the kind of guidance block.
- GuidanceBlock: A single block of guidance (heading + items + metadata).
- RunGuidance: Container for all guidance blocks for a run.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class BlockKind(StrEnum):
    """Kind of guidance block in a run playbook."""

    INVENTORY = "inventory"
    TRIGGER_PROMPTS = "trigger_prompts"
    DEPLOYMENT_STEPS = "deployment_steps"
    MONITORING = "monitoring"
    INTERPRETATION = "interpretation"
    FACTORS = "factors"


@dataclass
class GuidanceBlock:
    """A single block of run-level guidance.

    Attributes:
        kind: The kind of guidance this block represents.
        label: Human-readable heading for the block.
        items: Bullet items or instruction lines.
        metadata: Flexible key-value data for structured content like
            file inventory rows or trigger prompt profiles.
    """

    kind: BlockKind
    label: str
    items: list[str]
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a plain dict.

        Returns:
            Dict with string enum values and list/dict copies.
        """
        return {
            "kind": self.kind.value,
            "label": self.label,
            "items": list(self.items),
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GuidanceBlock:
        """Deserialize from a plain dict.

        Args:
            data: Dict with kind, label, items, metadata.

        Returns:
            A GuidanceBlock instance.

        Raises:
            ValueError: If required keys are missing or enum values are invalid.
            TypeError: If items or metadata have wrong types.
        """
        missing = [k for k in ("kind", "label") if k not in data]
        if missing:
            msg = f"GuidanceBlock missing required keys: {missing}"
            raise ValueError(msg)
        try:
            kind = BlockKind(data["kind"])
        except ValueError:
            msg = f"Invalid BlockKind value: {data['kind']!r}"
            raise ValueError(msg) from None

        items = data.get("items", [])
        if not isinstance(items, list):
            msg = f"GuidanceBlock 'items' must be a list, got {type(items).__name__}"
            raise TypeError(msg)

        metadata = data.get("metadata", {})
        if not isinstance(metadata, dict):
            msg = f"GuidanceBlock 'metadata' must be a dict, got {type(metadata).__name__}"
            raise TypeError(msg)

        return cls(
            kind=kind,
            label=data["label"],
            items=list(items),
            metadata=dict(metadata),
        )


@dataclass
class RunGuidance:
    """Complete run-level guidance for a workflow run.

    Attributes:
        blocks: Ordered list of guidance blocks.
        schema_version: Serialization format version.
        generated_at: ISO timestamp of when this guidance was generated.
        module: Which module generated this guidance.
    """

    blocks: list[GuidanceBlock] = field(default_factory=list)
    schema_version: int = 1
    generated_at: str = ""
    module: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a plain dict.

        Returns:
            Dict suitable for JSON serialization.
        """
        return {
            "blocks": [b.to_dict() for b in self.blocks],
            "schema_version": self.schema_version,
            "generated_at": self.generated_at,
            "module": self.module,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RunGuidance:
        """Deserialize from a plain dict.

        Fail-soft: unknown schema_version returns a fallback RunGuidance with
        a single block containing a not-supported message rather than raising.

        Args:
            data: Dict with blocks, schema_version, generated_at, module.

        Returns:
            A RunGuidance instance.
        """
        version = data.get("schema_version", 1)
        if version != 1:
            return cls(
                blocks=[
                    GuidanceBlock(
                        kind=BlockKind.FACTORS,
                        label="Unsupported Format",
                        items=["Guidance format not supported by this version"],
                    )
                ],
                schema_version=version,
                generated_at=data.get("generated_at", ""),
                module=data.get("module", ""),
            )

        raw_blocks = data.get("blocks", [])
        if not isinstance(raw_blocks, list):
            msg = f"RunGuidance 'blocks' must be a list, got {type(raw_blocks).__name__}"
            raise TypeError(msg)

        return cls(
            blocks=[GuidanceBlock.from_dict(b) for b in raw_blocks],
            schema_version=version,
            generated_at=data.get("generated_at", ""),
            module=data.get("module", ""),
        )

    @classmethod
    def create(cls, blocks: list[GuidanceBlock], module: str) -> RunGuidance:
        """Create a new RunGuidance with the current timestamp.

        Args:
            blocks: Guidance blocks to include.
            module: Module name generating this guidance.

        Returns:
            A RunGuidance with generated_at set to now.
        """
        return cls(
            blocks=blocks,
            generated_at=datetime.datetime.now(datetime.UTC).isoformat(),
            module=module,
        )
